# Generated by Django 4.2.7 on 2025-06-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LeaderboardEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("xp", "Experience Points"),
                            ("zones", "Zones Owned"),
                            ("attacks", "Successful Attacks"),
                            ("level", "User Level"),
                        ],
                        max_length=10,
                    ),
                ),
                ("score", models.PositiveIntegerField()),
                ("rank", models.PositiveIntegerField()),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["category", "rank"],
            },
        ),
        migrations.CreateModel(
            name="LeaderboardSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("xp", "Experience Points"),
                            ("zones", "Zones Owned"),
                            ("attacks", "Successful Attacks"),
                            ("level", "User Level"),
                        ],
                        max_length=10,
                    ),
                ),
                ("snapshot_date", models.DateTimeField(auto_now_add=True)),
                ("data", models.JSONField()),
            ],
            options={
                "ordering": ["-snapshot_date"],
                "indexes": [
                    models.Index(
                        fields=["category", "snapshot_date"],
                        name="leaderboard_categor_27ad70_idx",
                    )
                ],
            },
        ),
    ]
