# Generated by Django 4.2.7 on 2025-06-13 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("leaderboard", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="leaderboardentry",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leaderboard_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="leaderboardentry",
            index=models.Index(
                fields=["category", "rank"], name="leaderboard_categor_956cbf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leaderboardentry",
            index=models.Index(
                fields=["category", "score"], name="leaderboard_categor_6ef1fa_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="leaderboardentry",
            unique_together={("user", "category")},
        ),
    ]
