# Generated by Django 4.2.7 on 2025-06-13 07:23

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attacker_power", models.PositiveIntegerField()),
                ("defender_power", models.PositiveIntegerField(default=0)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("success", "Successful Attack"),
                            ("failed", "Failed Attack"),
                            ("cooldown", "Attack on Cooldown"),
                            ("invalid", "Invalid Attack"),
                        ],
                        max_length=10,
                    ),
                ),
                ("success", models.BooleanField()),
                (
                    "attacker_location",
                    django.contrib.gis.db.models.fields.PointField(srid=4326),
                ),
                ("xp_gained", models.PositiveIntegerField(default=0)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="AttackCooldown",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_attack", models.DateTimeField(auto_now_add=True)),
                ("cooldown_until", models.DateTimeField()),
            ],
        ),
    ]
