# Generated by Django 4.2.7 on 2025-06-13 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("zones", "0001_initial"),
        ("attacks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="attackcooldown",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="attackcooldown",
            name="zone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="zones.zone"
            ),
        ),
        migrations.AddField(
            model_name="attack",
            name="attacker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attacks_made",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="attack",
            name="defender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attacks_received",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="attack",
            name="zone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attacks",
                to="zones.zone",
            ),
        ),
        migrations.AddIndex(
            model_name="attackcooldown",
            index=models.Index(
                fields=["user", "cooldown_until"], name="attacks_att_user_id_4276c3_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attackcooldown",
            unique_together={("user", "zone")},
        ),
        migrations.AddIndex(
            model_name="attack",
            index=models.Index(
                fields=["attacker", "timestamp"], name="attacks_att_attacke_7df890_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attack",
            index=models.Index(
                fields=["zone", "timestamp"], name="attacks_att_zone_id_68c441_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attack",
            index=models.Index(
                fields=["defender", "timestamp"], name="attacks_att_defende_e49c7e_idx"
            ),
        ),
    ]
